import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { supabase } from "@/lib/supabaseClient";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useFormDraft } from "@/hooks/useFormDraft";
import DraftPrompt from "@/components/DraftPrompt";
import { useKeepScreenAwake } from "@/hooks/useKeepScreenAwake";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Loader2, CheckCircle, AlertCircle, Eye, EyeOff } from "lucide-react";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { syncTraineeToLead } from "@/lib/lifeos/lifeos-api";

const INITIAL_DATA = {
  fullName: "",
  phone: "",
  email: "",
  password: "",
  birthDate: "",
  joinDate: "",
  address: "",
  coachNotes: "",
  clientStatus: "לקוח פעיל",
  clientType: "regular",
};

export default function AddTraineeDialog({ open, onClose, initialData = null }) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(true);
  const [coach, setCoach] = useState(null);

  // Prefill (e.g. from a lead) overrides the blank defaults but is
  // shallow-merged so any field the caller didn't set stays empty.
  const seedData = initialData ? { ...INITIAL_DATA, ...initialData } : INITIAL_DATA;

  const {
    data: formData, setData: setFormData,
    hasDraft, keepDraft, discardDraft, clearDraft,
  } = useFormDraft('AddTrainee', coach?.id, open, seedData);

  useKeepScreenAwake(open);

  useEffect(() => {
    // Load current coach for notifications
    base44.auth.me().then(setCoach).catch(console.error);
  }, []);

  // Calculate age automatically
  const calculateAge = (birthDate) => {
    if (!birthDate) return "";
    const today = new Date();
    const birth = new Date(birthDate);
    let age = today.getFullYear() - birth.getFullYear();
    const m = today.getMonth() - birth.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) {
      age--;
    }
    return age;
  };

  const handleChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async () => {
    if (!formData.fullName) {
      toast.error("נא למלא שם מלא");
      return;
    }

    const email = formData.email?.trim() || `${formData.fullName.replace(/\s+/g, '.').toLowerCase()}.${Date.now()}@athletigo.app`;
    const password = formData.password || `Ath${Date.now().toString(36)}!`;
    const wasAutoGenerated = !formData.email?.trim();

    setLoading(true);

    try {
      const age = calculateAge(formData.birthDate);

      // Save coach session before signUp (signUp switches the active session)
      const { data: { session: coachSession } } = await supabase.auth.getSession();

      // Step 1: Create auth user via signUp
      const { data: authData, error: signUpError } = await supabase.auth.signUp({
        email,
        password,
        options: { data: { full_name: formData.fullName, role: 'trainee' } }
      });

      // Immediately restore coach session so the app doesn't redirect
      if (coachSession) {
        await supabase.auth.setSession({
          access_token: coachSession.access_token,
          refresh_token: coachSession.refresh_token,
        });
      }

      if (signUpError) {
        let msg = signUpError.message;
        if (msg.includes("already registered") || msg.includes("duplicate")) msg = "משתמש עם אימייל זה כבר קיים";
        else if (msg.includes("password")) msg = "הסיסמה חייבת להכיל לפחות 6 תווים";
        toast.error("שגיאה ביצירת המתאמן: " + msg);
        return;
      }

      if (!authData.user) {
        toast.error("שגיאה ביצירת המתאמן — לא התקבל משתמש");
        return;
      }

      // Every new trainee starts at 'onboarding' regardless of the
      // casual/active type the coach picked. They flow through the
      // /Onboarding page (welcome + personal info form + medical
      // questionnaire) which sets onboarding_completed=true and
      // client_status='casual' on submit. The coach can later flip
      // them to 'active' from the profile badge once they're onboard.
      // The legacy "casual" type still seeds minimal perms +
      // legacy Hebrew client_type for back-compat reads.
      const isCasual = formData.clientType === 'casual';
      const clientStatusValue = 'onboarding';

      // Step 2: Upsert profile into users table.
      // Why upsert instead of insert: a `handle_new_user` trigger on
      // auth.users may already have created a minimal public.users row
      // by the time we get here, which makes a plain INSERT fail with
      // a duplicate-key 422/409. Upsert with onConflict='id' merges
      // our richer payload onto whatever the trigger seeded.
      //
      // birth_date is sent as the raw HTML5 date string (YYYY-MM-DD)
      // because the column is DATE — wrapping it in
      // `new Date(...).toISOString()` produces a full TIMESTAMP that
      // PostgREST rejects with 422 for a DATE column.
      const corePayload = {
        id: authData.user.id,
        email,
        full_name: formData.fullName,
        role: 'trainee',
        client_status: clientStatusValue,
        coach_id: coach?.id || null,
        onboarding_completed: false,
        created_at: new Date().toISOString(),
      };
      const extraPayload = {
        phone: formData.phone || null,
        birth_date: formData.birthDate || null,
        age: age ? parseInt(age) : null,
        join_date: formData.joinDate || new Date().toISOString().split('T')[0],
        address: formData.address || null,
        coach_notes: formData.coachNotes || null,
        client_type: isCasual ? 'מתאמן מזדמן' : 'לקוח פעיל',
      };

      let { error: profileError } = await supabase
        .from('users')
        .upsert({ ...corePayload, ...extraPayload }, { onConflict: 'id' });

      if (profileError) {
        // One column in the extras is missing or violates a constraint
        // in this install. Fall back to upserting the core fields, then
        // patch each extra individually so the failures don't cascade.
        // Mirrors the per-field retry pattern in TraineeProfile.jsx.
        console.warn('[AddTrainee] bulk upsert failed, retrying per-field:', profileError.message);
        const { error: coreError } = await supabase
          .from('users')
          .upsert(corePayload, { onConflict: 'id' });
        if (coreError) {
          toast.error("שגיאה בשמירת הפרופיל: " + coreError.message);
          return;
        }
        const failedFields = [];
        for (const [k, v] of Object.entries(extraPayload)) {
          if (v == null) continue;
          const { error: fieldError } = await supabase
            .from('users')
            .update({ [k]: v })
            .eq('id', authData.user.id);
          if (fieldError) {
            console.warn(`[AddTrainee] field "${k}" rejected:`, fieldError.message);
            failedFields.push(k);
          }
        }
        if (failedFields.length) {
          toast.warning(`חלק מהשדות לא נשמרו: ${failedFields.join(', ')}`);
        }
        profileError = null;
      }

      // Cross-app sync (best-effort, never blocks): a new trainee is
      // an already-converted lead in the financial app's funnel.
      if (coach?.id) {
        try {
          await syncTraineeToLead(coach.id, {
            full_name: formData.fullName,
            phone: formData.phone || null,
            email: email || null,
          });
        } catch (e) {
          console.warn('[AddTrainee] syncTraineeToLead failed:', e?.message);
        }
      }

      // Seed a trainee_permissions row. CASUAL trainees only get
      // send_messages so they can talk to the coach about their
      // first session — every other tab is gated until a package
      // is sold (PackageFormDialog flips them to active and opens
      // all toggles). ACTIVE trainees get the full set on day one
      // (the legacy default before the casual pipeline existed).
      if (coach?.id && authData.user?.id) {
        try {
          const minimalPerms = {
            view_baseline: false,
            view_plan: false,
            view_progress: false,
            view_documents: false,
            edit_metrics: false,
            send_videos: false,
            send_messages: true,
            view_training_plan: false,
            view_records: false,
          };
          const fullPerms = Object.fromEntries(
            Object.keys(minimalPerms).map((k) => [k, true])
          );
          await supabase.from('trainee_permissions').upsert({
            coach_id: coach.id,
            trainee_id: authData.user.id,
            ...(isCasual ? minimalPerms : fullPerms),
          }, { onConflict: 'coach_id,trainee_id' });
        } catch (e) {
          console.warn('[AddTrainee] trainee_permissions seed failed:', e?.message);
        }
      }

      // Step 3: Send notification to coach
      if (coach) {
        try {
          await base44.entities.Notification.create({
            user_id: coach.id, type: 'new_trainee',
            title: 'מתאמן חדש נוסף',
            message: `המתאמן ${formData.fullName} נוסף למערכת.`,
            is_read: false
          });
        } catch {}
      }

      // (Removed duplicate sync block — syncTraineeToLead above
      //  already covers the leads-table mirror. The previous code
      //  called both syncTraineeToLead AND recordTraineeAsConvertedLead,
      //  which were different names for the same operation, so this
      //  ran twice on every trainee add.)

      // Step 4: Force-refetch ALL lists — await to ensure dashboard counts update before dialog closes
      await Promise.all([
        queryClient.refetchQueries({ queryKey: ['all-trainees'] }),
        queryClient.refetchQueries({ queryKey: ['all-services-list'] }),
        queryClient.refetchQueries({ queryKey: ['all-sessions'] }),
        queryClient.refetchQueries({ queryKey: ['training-plans'] }),
        queryClient.refetchQueries({ queryKey: ['leads'] }),
      ]);

      if (wasAutoGenerated) {
        toast.success(`המתאמן "${formData.fullName}" נוצר בהצלחה`);
      } else {
        toast.success(`המתאמן נוצר — אימייל: ${email}, סיסמא: ${password}`);
      }
      clearDraft();
      onClose();

    } catch (error) {
      toast.error("שגיאה ביצירת המתאמן: " + (error?.message || "נסה שוב"));
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      {open && hasDraft && (
        <DraftPrompt
          formLabel="טופס יצירת מתאמן"
          onResume={keepDraft}
          onNew={discardDraft}
          onDiscard={discardDraft}
        />
      )}
    <Dialog open={open} onOpenChange={(isOpen) => !loading && onClose(isOpen)}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="text-2xl font-black text-[#222]">
            יצירת מתאמן חדש
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Type picker */}
          <div className="grid grid-cols-2 gap-3">
            <button type="button" onClick={() => handleChange('clientType', 'regular')}
              style={{ padding: '14px', borderRadius: 12, border: formData.clientType === 'regular' ? '2px solid #FF6F20' : '2px solid #eee', background: formData.clientType === 'regular' ? '#FFF0E8' : 'white', cursor: 'pointer', textAlign: 'center' }}>
              <div style={{ fontSize: 24, marginBottom: 4 }}>👤</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: formData.clientType === 'regular' ? '#FF6F20' : '#333' }}>מתאמן רגיל</div>
              <div style={{ fontSize: 11, color: '#999' }}>גישה לאפליקציה</div>
            </button>
            <button type="button" onClick={() => handleChange('clientType', 'casual')}
              style={{ padding: '14px', borderRadius: 12, border: formData.clientType === 'casual' ? '2px solid #EAB308' : '2px solid #eee', background: formData.clientType === 'casual' ? '#FEF9C3' : 'white', cursor: 'pointer', textAlign: 'center' }}>
              <div style={{ fontSize: 24, marginBottom: 4 }}>🏃</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: formData.clientType === 'casual' ? '#92400E' : '#333' }}>מזדמן</div>
              <div style={{ fontSize: 11, color: '#999' }}>בלי גישה — לתיעוד</div>
            </button>
          </div>

          {/* Basic Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">שם מלא *</Label>
              <Input 
                value={formData.fullName}
                onChange={(e) => handleChange('fullName', e.target.value)}
                className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50]"
                placeholder="הקלד את שמך המלא"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">אימייל</Label>
              <Input
                type="email"
                value={formData.email}
                onChange={(e) => handleChange('email', e.target.value)}
                className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50]"
                placeholder="אופציונלי — ייווצר אוטומטית אם ריק"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">סיסמה</Label>
              <div className="relative">
                <Input
                  type={showPassword ? "text" : "password"}
                  value={formData.password}
                  onChange={(e) => handleChange('password', e.target.value)}
                  className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50] pl-10"
                  placeholder="אופציונלי — תיווצר אוטומטית אם ריק"
                  autoComplete="new-password"
                />
                <button type="button" onClick={() => setShowPassword(!showPassword)}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">טלפון</Label>
              <Input 
                value={formData.phone}
                onChange={(e) => handleChange('phone', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
                placeholder="הקלד מספר טלפון"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">תאריך לידה</Label>
              <Input 
                type="date"
                value={formData.birthDate}
                onChange={(e) => handleChange('birthDate', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
              />
              {formData.birthDate && (
                <span className="text-xs text-gray-500 mt-1 block">
                  גיל מחושב: {calculateAge(formData.birthDate)}
                </span>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">תאריך הצטרפות</Label>
              <Input 
                type="date"
                value={formData.joinDate}
                onChange={(e) => handleChange('joinDate', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">סטטוס לקוח</Label>
              <Select 
                value={formData.clientStatus} 
                onValueChange={(val) => handleChange('clientStatus', val)}
              >
                <SelectTrigger className="h-12 rounded-xl border-gray-200">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ליד חדש">ליד חדש</SelectItem>
                  <SelectItem value="לקוח פעיל">לקוח פעיל</SelectItem>
                  <SelectItem value="לקוח לא פעיל">לקוח לא פעיל</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div>
            <Label className="mb-2 block font-bold text-gray-700">כתובת</Label>
            <Input 
              value={formData.address}
              onChange={(e) => handleChange('address', e.target.value)}
              className="h-12 rounded-xl border-gray-200"
              placeholder="רחוב, מספר, עיר"
            />
          </div>

          <div>
            <Label className="mb-2 block font-bold text-gray-700">הערות מאמן</Label>
            <Textarea 
              value={formData.coachNotes}
              onChange={(e) => handleChange('coachNotes', e.target.value)}
              className="min-h-[100px] rounded-xl border-gray-200 resize-none"
              placeholder="הערות פנימיות..."
            />
          </div>

          <div className="flex gap-4 mt-6">
            <Button
              variant="outline"
              onClick={() => onClose()}
              className="flex-1 h-12 rounded-xl border-gray-200"
              disabled={loading}
            >
              ביטול
            </Button>
            <Button 
              onClick={handleSubmit}
              className="flex-1 h-12 rounded-xl bg-[#4CAF50] hover:bg-[#43A047] text-white"
              disabled={loading}
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin ml-2" />
                  שומר...
                </>
              ) : (
                <>
                  <CheckCircle className="w-5 h-5 ml-2" />
                  שמור מתאמן
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
    </>
  );
}