import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { supabase } from "@/lib/supabaseClient";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useFormPersistence } from "../hooks/useFormPersistence";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Loader2, CheckCircle, AlertCircle, Eye, EyeOff } from "lucide-react";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";

export default function AddTraineeDialog({ open, onClose }) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(true);
  const [coach, setCoach] = useState(null);

  const defaultFormData = {
    fullName: "",
    phone: "",
    email: "",
    password: "",
    birthDate: "",
    joinDate: new Date().toISOString().split('T')[0],
    address: "",
    coachNotes: "",
    clientStatus: "לקוח פעיל"
  };

  const [formData, setFormData, clearDraft, draftExists] = useFormPersistence("trainee_form_new", defaultFormData);

  useEffect(() => {
    // Load current coach for notifications
    base44.auth.me().then(setCoach).catch(console.error);
  }, []);

  // Calculate age automatically
  const calculateAge = (birthDate) => {
    if (!birthDate) return "";
    const today = new Date();
    const birth = new Date(birthDate);
    let age = today.getFullYear() - birth.getFullYear();
    const m = today.getMonth() - birth.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) {
      age--;
    }
    return age;
  };

  const handleChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async () => {
    if (!formData.fullName) {
      toast.error("נא למלא שם מלא");
      return;
    }

    const email = formData.email?.trim() || `${formData.fullName.replace(/\s+/g, '.').toLowerCase()}.${Date.now()}@athletigo.app`;
    const password = formData.password || `Ath${Date.now().toString(36)}!`;
    const wasAutoGenerated = !formData.email?.trim();

    setLoading(true);

    try {
      const age = calculateAge(formData.birthDate);

      // Save coach session before signUp (signUp switches the active session)
      const { data: { session: coachSession } } = await supabase.auth.getSession();

      // Step 1: Create auth user via signUp
      const { data: authData, error: signUpError } = await supabase.auth.signUp({
        email,
        password,
        options: { data: { full_name: formData.fullName, role: 'trainee' } }
      });

      // Immediately restore coach session so the app doesn't redirect
      if (coachSession) {
        await supabase.auth.setSession({
          access_token: coachSession.access_token,
          refresh_token: coachSession.refresh_token,
        });
      }

      if (signUpError) {
        let msg = signUpError.message;
        if (msg.includes("already registered") || msg.includes("duplicate")) msg = "משתמש עם אימייל זה כבר קיים";
        else if (msg.includes("password")) msg = "הסיסמה חייבת להכיל לפחות 6 תווים";
        toast.error("שגיאה ביצירת המתאמן: " + msg);
        return;
      }

      if (!authData.user) {
        toast.error("שגיאה ביצירת המתאמן — לא התקבל משתמש");
        return;
      }

      // Step 2: Insert profile into users table
      const { error: profileError } = await supabase.from('users').insert({
        id: authData.user.id,
        email,
        full_name: formData.fullName,
        phone: formData.phone || null,
        birth_date: formData.birthDate ? new Date(formData.birthDate).toISOString() : null,
        age: age ? parseInt(age) : null,
        join_date: formData.joinDate || new Date().toISOString().split('T')[0],
        address: formData.address || null,
        coach_notes: formData.coachNotes || null,
        client_status: formData.clientStatus || 'לקוח פעיל',
        coach_id: coach?.id || null,
        role: 'trainee',
        onboarding_completed: true,
        created_at: new Date().toISOString(),
      });

      if (profileError) {
        toast.error("שגיאה בשמירת הפרופיל: " + profileError.message);
        return;
      }

      // Step 3: Send notification to coach
      if (coach) {
        try {
          await base44.entities.Notification.create({
            user_id: coach.id, type: 'new_trainee',
            title: 'מתאמן חדש נוסף',
            message: `המתאמן ${formData.fullName} נוסף למערכת.`,
            is_read: false
          });
        } catch {}
      }

      // Step 4: Refresh lists
      queryClient.invalidateQueries({ queryKey: ['all-trainees'] });
      queryClient.invalidateQueries({ queryKey: ['users-trainees'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard-stats'] });

      if (wasAutoGenerated) {
        toast.success(`המתאמן "${formData.fullName}" נוצר בהצלחה`);
      } else {
        toast.success(`המתאמן נוצר — אימייל: ${email}, סיסמא: ${password}`);
      }
      clearDraft();
      onClose();

    } catch (error) {
      toast.error("שגיאה ביצירת המתאמן: " + (error?.message || "נסה שוב"));
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !loading && onClose(isOpen)}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="text-2xl font-black text-[#222]">
            יצירת מתאמן חדש
          </DialogTitle>
          {draftExists && (
            <div className="text-sm text-gray-500 mt-1">
              טיוטה שמורה
            </div>
          )}
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Basic Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">שם מלא *</Label>
              <Input 
                value={formData.fullName}
                onChange={(e) => handleChange('fullName', e.target.value)}
                className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50]"
                placeholder="הקלד את שמך המלא"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">אימייל</Label>
              <Input
                type="email"
                value={formData.email}
                onChange={(e) => handleChange('email', e.target.value)}
                className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50]"
                placeholder="אופציונלי — ייווצר אוטומטית אם ריק"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">סיסמה</Label>
              <div className="relative">
                <Input
                  type={showPassword ? "text" : "password"}
                  value={formData.password}
                  onChange={(e) => handleChange('password', e.target.value)}
                  className="h-12 rounded-xl border-gray-200 focus:border-[#4CAF50] focus:ring-[#4CAF50] pl-10"
                  placeholder="אופציונלי — תיווצר אוטומטית אם ריק"
                  autoComplete="new-password"
                />
                <button type="button" onClick={() => setShowPassword(!showPassword)}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                  {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">טלפון</Label>
              <Input 
                value={formData.phone}
                onChange={(e) => handleChange('phone', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
                placeholder="הקלד מספר טלפון"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">תאריך לידה</Label>
              <Input 
                type="date"
                value={formData.birthDate}
                onChange={(e) => handleChange('birthDate', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
              />
              {formData.birthDate && (
                <span className="text-xs text-gray-500 mt-1 block">
                  גיל מחושב: {calculateAge(formData.birthDate)}
                </span>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label className="mb-2 block font-bold text-gray-700">תאריך הצטרפות</Label>
              <Input 
                type="date"
                value={formData.joinDate}
                onChange={(e) => handleChange('joinDate', e.target.value)}
                className="h-12 rounded-xl border-gray-200"
              />
            </div>
            <div>
              <Label className="mb-2 block font-bold text-gray-700">סטטוס לקוח</Label>
              <Select 
                value={formData.clientStatus} 
                onValueChange={(val) => handleChange('clientStatus', val)}
              >
                <SelectTrigger className="h-12 rounded-xl border-gray-200">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ליד חדש">ליד חדש</SelectItem>
                  <SelectItem value="לקוח פעיל">לקוח פעיל</SelectItem>
                  <SelectItem value="לקוח לא פעיל">לקוח לא פעיל</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div>
            <Label className="mb-2 block font-bold text-gray-700">כתובת</Label>
            <Input 
              value={formData.address}
              onChange={(e) => handleChange('address', e.target.value)}
              className="h-12 rounded-xl border-gray-200"
              placeholder="רחוב, מספר, עיר"
            />
          </div>

          <div>
            <Label className="mb-2 block font-bold text-gray-700">הערות מאמן</Label>
            <Textarea 
              value={formData.coachNotes}
              onChange={(e) => handleChange('coachNotes', e.target.value)}
              className="min-h-[100px] rounded-xl border-gray-200 resize-none"
              placeholder="הערות פנימיות..."
            />
          </div>

          <div className="flex gap-4 mt-6">
            <Button 
              variant="outline" 
              onClick={() => {
                clearDraft();
                onClose();
              }}
              className="flex-1 h-12 rounded-xl border-gray-200"
              disabled={loading}
            >
              ביטול
            </Button>
            <Button 
              onClick={handleSubmit}
              className="flex-1 h-12 rounded-xl bg-[#4CAF50] hover:bg-[#43A047] text-white"
              disabled={loading}
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin ml-2" />
                  שומר...
                </>
              ) : (
                <>
                  <CheckCircle className="w-5 h-5 ml-2" />
                  שמור מתאמן
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}